### ISSUE TITLE
Expand the field of application?

### ISSUE THREAD

**Issue by fzara** [andyofmelbourne/speckle-tracking#2]
I have some ideas regarding the application of your software in the biomedicine field.
Are you interested?

**Comment by andyofmelbourne** [comment]
Certainly, what did you have in mind?

**Comment by fzara** [comment]
Do you mind if we talk via mail/skype/whatever?

**Comment by andyofmelbourne** [comment]
Sure. My email is: morganaj@unimelb.edu.au.
